drop table if exists order_table CASCADE;

drop table if exists orderdetail_table CASCADE;

drop table if exists product_table CASCADE;

create table order_table (
       id bigint generated by default as identity,
        version bigint,
        customer_address varchar(255),
        customer_name varchar(255),
        order_detail_id bigint,
        primary key (id)
);

create table orderdetail_table (
       id bigint generated by default as identity,
        version bigint,
        quantity bigint,
        product_id bigint not null,
        primary key (id)
    );
    
    create table product_table (
       id bigint generated by default as identity,
        version bigint,
        description varchar(255),
        name varchar(255),
        quantity bigint,
        primary key (id)
    );

    
    alter table order_table 
       add constraint FKlaorl6sf6t4r9ccihbdnbh4u4 
       foreign key (order_detail_id) 
       references orderdetail_table;

    
    alter table orderdetail_table 
       add constraint FKn85f4r614m4xut6gg25n81mfn 
       foreign key (product_id) 
       references product_table;